import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from "next";
import { BrandsProvider } from '@/context/BrandsContext';
import { ResultsProvider } from '@/context/ResultsContext';
import { Roboto } from "next/font/google";
import { GlobalStyles } from '@/styles/global';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={roboto.className}>
          <GlobalStyles />
          <ResultsProvider>
            <BrandsProvider>
              <AppRouterCacheProvider>
                {children}
              </AppRouterCacheProvider>
            </BrandsProvider>
          </ResultsProvider>
        </body>
      </html>
  );
}
