import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Roboto } from "next/font/google";
import type { Metadata } from "next";
import { BrandsProvider, ResultsProvider } from '@/context';
import { GlobalStyles } from '@/styles/global';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700']
})

export const metadata: Metadata = {
  title: "Buscador de Preços Tabela Fipe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>
        <body className={roboto.className}>
          <GlobalStyles />
          <ResultsProvider>
            <BrandsProvider>
              <AppRouterCacheProvider>
                {children}
              </AppRouterCacheProvider>
            </BrandsProvider>
          </ResultsProvider>
        </body>
      </html>
  );
}
